=== forcedotcom/schemas/project-scratch-def.json/project-scratch-def.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://schemas.salesforce.com/project-scratch-def.json",
  "title": "Scratch Org Definition Configuration",
  "description": "The scratch org definition file contains the configuration values that determine the shape of the scratch org.",
  "type": "object",
  "required": ["edition"],
  "additionalProperties": true,
  "properties": {
    "orgName": {
      "$ref": "#/definitions/orgName"
    },
    "edition": {
      "$ref": "#/definitions/edition"
    },
    "country": {
      "$ref": "#/definitions/country"
    },
    "username": {
      "$ref": "#/definitions/username"
    },
    "adminEmail": {
      "$ref": "#/definitions/adminEmail"
    },
    "description": {
      "$ref": "#/definitions/description"
    },
    "hasSampleData": {
      "$ref": "#/definitions/hasSampleData"
    },
    "language": {
      "$ref": "#/definitions/language"
    },
    "features": {
      "$ref": "#/definitions/features"
    },
    "template": {
      "$ref": "#/definitions/template"
    },
    "settings": {
      "$ref": "#/definitions/settings"
    }
  },
  "definitions": {
    "orgName": {
      "type": "string",
      "title": "Organization Name",
      "description": "The name of the scratch org."
    },
    "edition": {
      "type": "string",
      "enum": ["Developer", "Group", "Professional", "Enterprise"]
    },
    "country": {
      "title": "Country",
      "type": "string",
      "description": "Dev Hub's country. If you want to override this value, enter the two-character, upper-case ISO-3166 country code (Alpha-2 code). You can find a full list of these codes at several sites, such as: https://www.iso.org/obp/ui/#search. This value sets the locale of the scratch org.",
      "maximum": 2
    },
    "username": {
      "title": "Username",
      "type": "string",
      "description": "A user name formatted like test-unique_identifier@orgName.net."
    },
    "adminEmail": {
      "title": "Administrator Email Address",
      "type": "string",
      "description": "Email address of the Dev Hub user making the scratch org creation request."
    },
    "description": {
      "title": "Description of the Org",
      "type": "string",
      "description": "The description is a good way to document the scratch orgâ€™s purpose. You can view or edit the description in the Dev Hub. From App Launcher, select Scratch Org Info or Active Scratch Orgs, then click the scratch org number."
    },
    "template": {
      "title": "Template ID",
      "type": "string",
      "description": "The template id for the scratch org shape. (Pilot)"
    },
    "language": {
      "title": "Default Language",
      "type": "string",
      "description": "Default language for the country. To override the language set by the Dev Hub locale, see Supported Languages (https://help.salesforce.com/articleView?id=faq_getstart_what_languages_does.htm&type=5&language=en_US) for the codes to use in this field.",
      "maximum": 5
    },
    "release": {
      "title": "Release",
      "type": "string",
      "description": "Same Salesforce release as the Dev Hub org. Options are preview or previous. Can use only during Salesforce release transition periods.",
      "enum": ["preview", "previous"]
    },
    "hasSampleData": {
      "type": "boolean",
      "title": "Include Sample Data",
      "description": "Valid values are true and false. False is the default, which creates an org without sample data.",
      "default": "false"
    },
    "features": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "settings": {
      "type": "object",
      "not": {
        "required": ["orgPreferenceSettings"]
      }
    }
  }
}

=== forcedotcom/schemas/examples/project-scratch-def/with-orgPreferenceSetting.json
{
  "orgName": "Dreamhouse",
  "edition": "Developer",
  "hasSampleData": false,
  "settings": {
    "orgPreferenceSettings": {
      "networksEnabled": true,

      "s1DesktopEnabled": true,

      "s1EncryptedStoragePref2": false
    },
    "omniChannelSettings": {
      "enableOmniChannel": true
    },
    "caseSettings": {
      "systemUserEmail": "support@acme.com"
    }
  }
}
